# Generated by Django 4.2.2 on 2024-05-17 07:46

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatchNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField(blank=True)),
                ('last_modified', models.DateTimeField()),
                ('version', models.CharField(max_length=20, unique=True)),
                ('notes', django_jsonform.models.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('joke_note', models.TextField(blank=True)),
            ],
        ),
    ]
