# Generated by Django 4.2.2 on 2024-05-15 13:03

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('changelog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patchnote',
            name='notes',
            field=django_jsonform.models.fields.ArrayField(base_field=models.TextField(), size=None),
        ),
    ]
