# Generated by Django 4.2.2 on 2024-05-04 02:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    database_operations = [
        migrations.AlterModelTable('UploadedFile', 'files_uploadedfile')
    ]

    state_operations = [
        migrations.DeleteModel('UploadedFile')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]