# Generated by Django 4.2.2 on 2024-05-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_twitchuser_options_alter_twitchuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchuser',
            name='is_affiliate',
            field=models.BooleanField(default=False),
        ),
    ]
