# Generated by Django 4.2.2 on 2024-05-02 00:45

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGPTVars',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.twitchuser')),
                ('clearsize', models.IntegerField(default=6)),
                ('conversation', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None)),
                ('showfull', models.BooleanField(default=False)),
                ('maxprompttokens', models.IntegerField(default=256)),
                ('tokensused', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GPTImageVars',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.twitchuser')),
                ('imagesize', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='SongReqVars',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.twitchuser')),
                ('emote', models.CharField(default='Okayge', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SongSkipVars',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.twitchuser')),
                ('emote', models.CharField(default='PepeLaugh', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='YTReqVars',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.twitchuser')),
                ('maxsecs', models.IntegerField(default=60)),
                ('mutespotify', models.BooleanField(default=True)),
            ],
        ),
    ]
