# Generated by Django 4.2.2 on 2024-05-04 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uploadedfile',
            table=None,
        ),
    ]
