# Generated by Django 4.2.13 on 2024-07-01 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('overlay', '0004_songreqoverlay_constant_songreqoverlay_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='YTReqOverlay',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('horizontal_anchor_pos', models.CharField(default='right', max_length=12)),
                ('vertical_anchor_pos', models.CharField(default='top', max_length=12)),
            ],
        ),
    ]
