# Generated by Django 4.2.13 on 2024-07-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0006_add_default_ytreqoverlay_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytreqoverlay',
            name='height',
            field=models.IntegerField(default=1080),
        ),
        migrations.AddField(
            model_name='ytreqoverlay',
            name='width',
            field=models.IntegerField(default=1920),
        ),
    ]
