# Generated by Django 4.2.2 on 2024-05-17 07:46

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('binded_to', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=None)),
                ('has_cooldown', models.BooleanField(default=True)),
                ('global_cooldown', models.IntegerField(default=10)),
                ('user_cooldown', models.IntegerField(default=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelPointReward',
            fields=[
                ('reward_id', models.TextField(primary_key=True, serialize=False)),
                ('reward_title', models.CharField(max_length=45)),
                ('color', models.CharField(max_length=10)),
                ('image', models.CharField(max_length=256)),
                ('bot_created', models.BooleanField(default=False)),
                ('binded_to', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
